export const metadata = {
    title: "Registrarse",
    description: "Generated by create next app",
    icon: ""
};

const Registrar = () => {
    return (
        <main className="">
            <h1 className="">Regístrate</h1>
            <div className="">
                <div className="">
                    <hr className="" />
                    <span>o</span>
                    <hr className="" />
                </div>
                <div className="">
                </div>
            </div>
        </main>
    )
}
export default Registrar;